'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Category
    Public Property CategoryID As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Avatar As String
    Public Property Status As Nullable(Of Boolean)
    Public Property IsDelete As Nullable(Of Boolean)
    Public Property MainCategoryID As Nullable(Of Integer)

    Public Overridable Property MainCategory As MainCategory
    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)

End Class
Partial Public Class Contact
    Public Property ContactPhoneNumber As String
    Public Property FullName As String
    Public Property Address As String
    Public Property Status As Nullable(Of Boolean)
    Public Property Email As String
    Public Property MoreDetail As String
    Public Property CreateTime As Nullable(Of Date)

End Class
Partial Public Class MainCategory
    Public Property MainCategoryID As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Position As Nullable(Of Integer)
    Public Property Avatar As String
    Public Property Status As Nullable(Of Boolean)
    Public Property IsDelete As Nullable(Of Boolean)
    Public Property IsPrimary As Nullable(Of Boolean)

    Public Overridable Property Categories As ICollection(Of Category) = New HashSet(Of Category)

End Class
Partial Public Class News
    Public Property NewsID As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Avatar As String
    Public Property Keywords As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property Status As Nullable(Of Boolean)
    Public Property IsDelete As Nullable(Of Boolean)
    Public Property Show As Nullable(Of Boolean)
    Public Property Detail As String
    Public Property NewsCategoryID As Nullable(Of Integer)

    Public Overridable Property NewsCategory As NewsCategory
    Public Overridable Property Relatives As ICollection(Of Relative) = New HashSet(Of Relative)

End Class
Partial Public Class NewsCategory
    Public Property NewsCategoryID As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Avatar As String
    Public Property Status As Nullable(Of Boolean)
    Public Property IsDelete As Nullable(Of Boolean)
    Public Property NewsMainCategoryID As Nullable(Of Integer)

    Public Overridable Property NewsMainCategory As NewsMainCategory
    Public Overridable Property News As ICollection(Of News) = New HashSet(Of News)

End Class
Partial Public Class NewsMainCategory
    Public Property NewsMainCategoryID As Integer
    Public Property Title As String
    Public Property Avatar As String
    Public Property Description As String
    Public Property Status As Nullable(Of Boolean)
    Public Property IsDelete As Nullable(Of Boolean)

    Public Overridable Property NewsCategories As ICollection(Of NewsCategory) = New HashSet(Of NewsCategory)

End Class
Partial Public Class Product
    Public Property ProductID As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Avatar As String
    Public Property BackGround As String
    Public Property OriginalPrice As Nullable(Of Integer)
    Public Property SalePrice As Nullable(Of Integer)
    Public Property Prepay As Nullable(Of Integer)
    Public Property Show As Nullable(Of Boolean)
    Public Property Choice As Nullable(Of Boolean)
    Public Property Status As Nullable(Of Boolean)
    Public Property IsDelete As Nullable(Of Boolean)
    Public Property CategoryID As Nullable(Of Integer)
    Public Property CreateTime As Nullable(Of Date)

    Public Overridable Property ProductCost As ProductCost
    Public Overridable Property ProductDetail As ProductDetail
    Public Overridable Property ProductPreviews As ICollection(Of ProductPreview) = New HashSet(Of ProductPreview)
    Public Overridable Property Relatives As ICollection(Of Relative) = New HashSet(Of Relative)
    Public Overridable Property Requests As ICollection(Of Request) = New HashSet(Of Request)
    Public Overridable Property ProductRelative As ProductRelative
    Public Overridable Property Category As Category
    Public Overridable Property ProductTechInfo As ProductTechInfo

End Class
Partial Public Class ProductCost
    Public Property ProductID As Integer
    Public Property VAT As Nullable(Of Single)
    Public Property PhiTruocBa As Nullable(Of Single)
    Public Property PhiDangKi As Nullable(Of Integer)
    Public Property PhiSuDungDuongBo As Nullable(Of Integer)
    Public Property PhiKiemDinh As Nullable(Of Integer)
    Public Property BaoHiemTNDS As Nullable(Of Integer)
    Public Property Locator As Nullable(Of Integer)
    Public Property TotalForRun As String

    Public Overridable Property Product As Product

End Class
Partial Public Class ProductDetail
    Public Property ProductID As Integer
    Public Property Detail As String
    Public Property CreateTime As Nullable(Of Date)
    Public Property CreateBy As String

    Public Overridable Property Product As Product

End Class
Partial Public Class ProductPreview
    Public Property ProductPreviewID As Integer
    Public Property Title As String
    Public Property Description As String
    Public Property Link As String
    Public Property ProductID As Nullable(Of Integer)

    Public Overridable Property Product As Product

End Class
Partial Public Class ProductRelative
    Public Property ProductID As Integer
    Public Property Keywords As String

    Public Overridable Property Product As Product

End Class
Partial Public Class ProductTechInfo
    Public Property ProductID As Integer
    Public Property Detail As String
    Public Property CreateBy As String
    Public Property CreateTime As Nullable(Of Date)

    Public Overridable Property Product As Product

End Class
Partial Public Class Relative
    Public Property RelativeID As Integer
    Public Property ProductID As Integer
    Public Property NewsID As Nullable(Of Integer)
    Public Property Status As Nullable(Of Boolean)
    Public Property Title As String
    Public Property Description As String

    Public Overridable Property Product As Product
    Public Overridable Property News As News

End Class
Partial Public Class Request
    Public Property RequestID As Integer
    Public Property PhoneNumber As String
    Public Property Name As String
    Public Property Address As String
    Public Property Email As String
    Public Property Note As String
    Public Property ProductID As Nullable(Of Integer)

    Public Overridable Property Product As Product

End Class
Partial Public Class sysdiagram
    Public Property name As String
    Public Property principal_id As Integer
    Public Property diagram_id As Integer
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
Partial Public Class User
    Public Property UserID As String
    Public Property Password As String
    Public Property Status As Nullable(Of Boolean)
    Public Property Avatar As String
    Public Property FullName As String

End Class
Partial Public Class Website
    Public Property WebsiteID As Integer
    Public Property WebsiteName As String
    Public Property WebsiteFavicon As String
    Public Property WebsiteIcon As String
    Public Property Address As String
    Public Property Description As String
    Public Property WebsiteDetail As String
    Public Property Hotline As String
    Public Property Email As String
    Public Property Map As String
    Public Property Facebook As String
    Public Property Zalo As String
    Public Property FacebookID As String
    Public Property Status As Nullable(Of Boolean)

End Class
Partial Public Class sp_helpdiagramdefinition_Result
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
Partial Public Class sp_helpdiagrams_Result
    Public Property Database As String
    Public Property Name As String
    Public Property ID As Integer
    Public Property Owner As String
    Public Property OwnerID As Integer

End Class
